"""empty message

Revision ID: 923a7d3c42b6
Revises: a7d5d4aa0a36
Create Date: 2020-07-19 13:24:42.840767

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '923a7d3c42b6'
down_revision = 'a7d5d4aa0a36'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Artist', sa.Column('genres', sa.ARRAY(sa.String()), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Artist', 'genres')
    # ### end Alembic commands ###
