"""empty message

Revision ID: a7d5d4aa0a36
Revises: c647a3df8ec5
Create Date: 2020-07-19 13:24:19.107667

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a7d5d4aa0a36'
down_revision = 'c647a3df8ec5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Artist', 'genres')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Artist', sa.Column('genres', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
