"""empty message

Revision ID: c647a3df8ec5
Revises: 8743215877f2
Create Date: 2020-07-14 02:05:29.776334

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c647a3df8ec5'
down_revision = '8743215877f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Artist', sa.Column('city_id', sa.Integer(), nullable=False))
    op.drop_constraint('Artist_city_fkey', 'Artist', type_='foreignkey')
    op.create_foreign_key(None, 'Artist', 'City', ['city_id'], ['id'])
    op.drop_column('Artist', 'city')
    op.add_column('Venue', sa.Column('city_id', sa.Integer(), nullable=False))
    op.drop_constraint('Venue_city_fkey', 'Venue', type_='foreignkey')
    op.create_foreign_key(None, 'Venue', 'City', ['city_id'], ['id'])
    op.drop_column('Venue', 'city')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Venue', sa.Column('city', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'Venue', type_='foreignkey')
    op.create_foreign_key('Venue_city_fkey', 'Venue', 'City', ['city'], ['id'])
    op.drop_column('Venue', 'city_id')
    op.add_column('Artist', sa.Column('city', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'Artist', type_='foreignkey')
    op.create_foreign_key('Artist_city_fkey', 'Artist', 'City', ['city'], ['id'])
    op.drop_column('Artist', 'city_id')
    # ### end Alembic commands ###
